name: Deploy Application
concurrency: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cli_version: '10.2.2'
      - run: npm ci

      - run: fastly compute publish --verbose -i --token ${{ secrets.FASTLY_API_KEY }}